### ISSUE TITLE
Typo in Section 4.2

### ISSUE THREAD

**Issue by forest1988** [THiyama/codespaces-st-contribute#1]
Hi, 
Thank you for creating the easy understandable tutorial.
There seems to be a minor point (typo).

```
- st_firesの資材を移動し`st.fires()`を作成します。下記の操作は、１つ目のターミナルで行います。
    - cd /workspaces/codespaces-st-contribute
    - cp -r st_fire/streamlit/* streamlit/
```

It is said `st_fires の資材`, but isn't it `st_fire の資材`？

Sorry if there is any misunderstanding.
May I open PR?

**Comment by THiyama** [comment]
Indeed, you are correct about the typo in the text. I would greatly appreciate it if you could make the correction and submit a PR. Thank you for bringing this to our attention.

**Comment by forest1988** [comment]
@THiyama 
Thank you for the response! I will soon open the PR.
